# Generated by Django 2.0.1 on 2018-01-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_alter_request_method_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='args',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='args'),
        ),
        migrations.AddField(
            model_name='request',
            name='data',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='data'),
        ),
        migrations.AddField(
            model_name='request',
            name='request_id',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='request_id'),
        ),
    ]
