# Generated by Django 2.0.1 on 2018-01-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_auto_20180126_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='json',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='json'),
        ),
    ]
