# Generated by Django 2.0.1 on 2018-01-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_request_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='json',
        ),
        migrations.AlterField(
            model_name='request',
            name='is_ajax',
            field=models.BooleanField(default=False, help_text='Whether this request was used via javascript.', verbose_name='is ajax'),
        ),
    ]
